name: TrimEffect
main: dev.zain.trimeffect.TrimEffectPlugin
version: 2.0.0-b5
description: Gives configurable potion effects for each trimmed armor piece worn. Effects do not stack.
author: Zain Development
api-version: 1.20
commands:
  te:
    description: Reloads TrimEffect config
    usage: /<command> reload
    permission: te.reload
    permission-message: You do not have permission to use this command.
    aliases: [trimeffect]

# This plugin requires Minecraft 1.20 or newer and is designed for Paper servers.
