# TrimEffect Plugin Configuration

trims:
  sentry:
    effects:
      - effect: SPEED
        amplifier: 1
        ambient: true
        particles: true
  dune:
    effects:
      - effect: STRENGTH
        amplifier: 0
        ambient: false
        particles: true
  coast:
    effects:
      - effect: REGENERATION
        amplifier: 0
        ambient: true
        particles: false
  wild:
    effects:
      - effect: JUMP_BOOST
        amplifier: 0
        ambient: true
        particles: true
  ward:
    effects:
      - effect: NIGHT_VISION
        amplifier: 0
        ambient: true
        particles: false
  eye:
    effects:
      - effect: HASTE
        amplifier: 0
        ambient: true
        particles: true
  vex:
    effects:
      - effect: LUCK
        amplifier: 0
        ambient: false
        particles: true
  rib:
    effects:
      - effect: RESISTANCE
        amplifier: 0
        ambient: true
        particles: true
  snout:
    effects:
      - effect: FIRE_RESISTANCE
        amplifier: 0
        ambient: true
        particles: true
  tide:
    effects:
      - effect: WATER_BREATHING
        amplifier: 0
        ambient: true
        particles: true
  spire:
    effects:
      - effect: LEVITATION
        amplifier: 0
        ambient: false
        particles: true
  silence:
    effects:
      - effect: INVISIBILITY
        amplifier: 0
        ambient: false
        particles: false
  raiser:
    effects:
      - effect: ABSORPTION
        amplifier: 0
        ambient: true
        particles: true
  wayfinder:
    effects:
      - effect: HERO_OF_THE_VILLAGE
        amplifier: 0
        ambient: true
        particles: true
  shaper:
    effects:
      - effect: CONDUIT_POWER
        amplifier: 0
        ambient: true
        particles: true
  host:
    effects:
      - effect: GLOWING
        amplifier: 0
        ambient: false
        particles: false
  bolt:
    effects:
      - effect: UNLUCK
        amplifier: 0
        ambient: true
        particles: true
  flow:
    effects:
      - effect: DOLPHINS_GRACE
        amplifier: 0
        ambient: true
        particles: true
